import type { RiskCase, RiskCaseDetail, Transaction } from '@/lib/types';

const now = new Date();
const ago = (minutes: number) =>
  new Date(now.getTime() - minutes * 60_000).toISOString();

export const demoTransactions: Transaction[] = [
  {
    transactionId: 'TX-928410',
    senderId: 'ACC-1738',
    receiverId: 'MER-NORTHSTAR',
    amount: 18450,
    currency: 'INR',
    deviceId: 'DEV-7729',
    ipAddress: '103.87.44.19',
    paymentMethod: 'UPI',
    timestamp: ago(1),
    status: 'BLOCKED',
    riskScore: 0.94,
    caseId: 'RISK-2408-017',
  },
  {
    transactionId: 'TX-928409',
    senderId: 'ACC-2251',
    receiverId: 'MER-PAPERCO',
    amount: 2199,
    currency: 'INR',
    deviceId: 'DEV-1190',
    ipAddress: '49.36.81.7',
    paymentMethod: 'CARD',
    timestamp: ago(3),
    status: 'APPROVED',
    riskScore: 0.14,
  },
  {
    transactionId: 'TX-928408',
    senderId: 'ACC-1739',
    receiverId: 'MER-BLUEOAK',
    amount: 76000,
    currency: 'INR',
    deviceId: 'DEV-7729',
    ipAddress: '103.87.44.19',
    paymentMethod: 'UPI',
    timestamp: ago(4),
    status: 'REVIEW',
    riskScore: 0.67,
    caseId: 'RISK-2408-016',
  },
  {
    transactionId: 'TX-928407',
    senderId: 'ACC-9812',
    receiverId: 'MER-MOSAIC',
    amount: 899,
    currency: 'INR',
    deviceId: 'DEV-8720',
    ipAddress: '117.205.2.90',
    paymentMethod: 'WALLET',
    timestamp: ago(6),
    status: 'APPROVED',
    riskScore: 0.07,
  },
  {
    transactionId: 'TX-928406',
    senderId: 'ACC-1741',
    receiverId: 'MER-NORTHSTAR',
    amount: 32200,
    currency: 'INR',
    deviceId: 'DEV-7729',
    ipAddress: '103.87.44.19',
    paymentMethod: 'CARD',
    timestamp: ago(8),
    status: 'REVIEW',
    riskScore: 0.81,
    caseId: 'RISK-2408-015',
  },
];

export const demoCases: RiskCase[] = [
  {
    caseId: 'RISK-2408-017',
    transactionId: 'TX-928410',
    accountId: 'ACC-1738',
    status: 'OPEN',
    severity: 'CRITICAL',
    ringRisk: 0.92,
    confidence: 0.96,
    recommendation: 'Block transaction and suspend linked accounts',
    createdAt: ago(1),
  },
  {
    caseId: 'RISK-2408-016',
    transactionId: 'TX-928408',
    accountId: 'ACC-1739',
    status: 'IN_REVIEW',
    severity: 'HIGH',
    ringRisk: 0.78,
    confidence: 0.89,
    recommendation: 'Escalate for analyst review',
    createdAt: ago(4),
  },
  {
    caseId: 'RISK-2408-015',
    transactionId: 'TX-928406',
    accountId: 'ACC-1741',
    status: 'OPEN',
    severity: 'HIGH',
    ringRisk: 0.81,
    confidence: 0.91,
    recommendation: 'Hold settlement and verify beneficiary',
    createdAt: ago(8),
  },
  {
    caseId: 'RISK-2408-014',
    transactionId: 'TX-928390',
    accountId: 'ACC-4407',
    status: 'RESOLVED',
    severity: 'MEDIUM',
    ringRisk: 0.54,
    confidence: 0.82,
    recommendation: 'Monitor future activity',
    createdAt: ago(37),
  },
];

export const demoCaseDetail: RiskCaseDetail = {
  ...demoCases[0],
  transactionRisk: 0.94,
  accountRisk: 0.83,
  behaviorRisk: 0.88,
  temporalRisk: 0.76,
  structuralRisk: 0.91,
  similarityRisk: 0.86,
  aiSummary:
    'A coordinated device cluster links eight newly created accounts to two payment instruments. Rapid beneficiary rotation, amount stepping, and shared network infrastructure strongly indicate an organized abuse ring.',
  updatedAt: ago(0),
  signals: [
    {
      type: 'SHARED_DEVICE',
      source: 'GRAPH',
      score: 0.96,
      description: 'Eight accounts authenticated from device DEV-7729.',
      evidence: '{"linkedAccounts":8}',
    },
    {
      type: 'VELOCITY_SPIKE',
      source: 'BEHAVIOR',
      score: 0.89,
      description: 'Six payments attempted within an eleven-minute window.',
    },
    {
      type: 'BENEFICIARY_ROTATION',
      source: 'STRUCTURAL',
      score: 0.84,
      description: 'Funds rotated across three recently onboarded merchants.',
    },
  ],
  decisions: [],
};
